STATE_RES_NAME: "${STATE_RES_NAME}"
gce_zone: "${gce_zone}"
gce_machine_type: "${gce_machine_type}"
gce_image: "${gce_image}"
gce_tag_Role: "${gce_tag_Role}"
gce_volume_size: ${gce_volume_size}
gce_count: ${gce_count}
GCE_EMAIL: "${GCE_EMAIL}"
GCE_CREDENTIALS_FILE_PATH: "${GCE_CREDENTIALS_FILE_PATH}"
GCE_PROJECT: "${GCE_PROJECT}"
